version: '3'

services:
  cdm-db:
    build:
      context: ./docker
      dockerfile: Dockerfile.cdm
    container_name: cdmDB
    restart: unless-stopped
    environment:
      DB_1_HOST: cdm-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: cdm
      PGDATA: /var/lib/postgresql/data/cdm
    networks:
      - app-network

  collection-manager-db:
    build:
      context: ./docker
      dockerfile: Dockerfile.collectionManagerDB
    container_name: collectionmanagerDB
    restart: unless-stopped
    environment:
      DB_2_HOST: collection-manager-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: collection-manager
      PGDATA: /var/lib/postgresql/data/collection-manager
    depends_on:
      - cdm-db
    networks:
      - app-network

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    container_name: server
    command: npm run start
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB_1: cdm
      POSTGRES_DB_2: collection-manager
      DB_1_HOST: cdm-db
      DB_2_HOST: collection-manager-db
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 5001:5001
    depends_on:
      - collection-manager-db
      - cdm-db
    networks:
      - app-network

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.client
    container_name: client
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - 8080:80
    depends_on:
      - collection-manager-db
      - cdm-db
      - server
    networks:
      - app-network

volumes:
  # collection-manager:
  #   driver: local
  server:
    driver: local

networks:
  app-network:
    driver: bridge
