FROM postgres:14.2-alpine
ENV POSTGRES_USER_2 postgres
ENV POSTGRES_PASSWORD_2 mypassword
ENV POSTGRES_DB_2 collection-manager
RUN rm -rf /var/lib/postgresql/data/*
COPY cm_dump.sql /docker-entrypoint-initdb.d/
RUN rm -rf /var/lib/postgresql/data/*
